services:
  localdb:
    image: postgres:14-alpine # you can pick the most recent version available
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=db

  testdb:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha_teste
      - POSTGRES_DB=db_test
